"""Le pays dont parle un article, pour l'afficher au-dessus du titre.

Chaque pays : son nom affiché, puis les mots qui le désignent (en français et en anglais, sans accents) :
nom, adjectifs, capitale, grandes villes, dirigeants très cités.
"""
LIEUX = {
    'Québec': "cegep cegeps caq saaq hydro-quebec quebec quebecois quebecoise quebecoises quebecois montreal laval gatineau sherbrooke trois-rivieres saguenay legault charlevoix gaspesie levis rimouski chicoutimi drummondville granby beauce laurentides outaouais abitibi estrie monteregie mauricie plamondon",
    'Canada': "canada canadien canadienne canadiens canadiennes canadian canadians ottawa toronto vancouver calgary edmonton winnipeg halifax ontario alberta saskatchewan manitoba nouvelle-ecosse nova scotia nouveau-brunswick colombie-britannique regina saskatoon victoria carney poilievre",
    'France': "france francais francaise francaises french paris marseille lyon toulouse bordeaux lille nantes strasbourg montpellier rennes grenoble toulon dijon nancy rouen caen brest marseillais parisien parisienne parisiens francilien francilienne ile-de-france bretagne normandie occitanie provence corse alsace auvergne aquitaine lycee lycees lyceen lyceens lyceenne lyceennes prefet prefete prefecture gendarmerie gendarmes sncf lecornu bayrou macron elysee matignon bardella melenchon",
    'États-Unis': "etats-unis americain americaine americains usa american americans washington trump new-york californie california texas floride florida chicago congres congress senate senat maison-blanche",
    'Royaume-Uni': "royaume-uni britannique britanniques uk britain british angleterre england london londres ecosse scotland starmer",
    'Belgique': "belgique belge belges belgium belgian bruxelles brussels",
    'Suisse': "suisse suisses switzerland swiss geneve geneva zurich berne lausanne",
    'Allemagne': "allemagne allemand allemande allemands germany german berlin munich merz",
    'Espagne': "espagne espagnol espagnole espagnols spain spanish madrid barcelone barcelona sanchez",
    'Italie': "italie italien italienne italiens italy italian rome milan venise naples meloni",
    'Portugal': "portugal portugais portugaise lisbonne lisbon porto",
    'Pays-Bas': "pays-bas neerlandais netherlands dutch amsterdam rotterdam",
    'Pologne': "pologne polonais polonaise poland polish varsovie warsaw",
    'Ukraine': "ukraine ukrainien ukrainienne ukrainiens ukrainian kiev kyiv kharkiv odessa zelensky zelenski",
    'Russie': "russie russe russes russia russian moscou moscow kremlin poutine putin",
    'Grèce': "grece grec grecque greece greek athenes athens crete",
    'Turquie': "turquie turc turque turkey turkish ankara istanbul erdogan",
    'Israël': "israel israelien israelienne israeliens israeli jerusalem tel-aviv netanyahu",
    'Palestine': "palestine palestinien palestinienne palestiniens palestinian gaza cisjordanie hamas",
    'Liban': "liban libanais libanaise lebanon lebanese beyrouth beirut hezbollah",
    'Syrie': "syrie syrien syrienne syria syrian damas damascus",
    'Iran': "iran iranien iranienne iraniens iranian teheran tehran",
    'Irak': "irak iraq irakien iraqi bagdad baghdad",
    'Arabie saoudite': "saoudite saoudien saoudienne saudi riyad riyadh",
    'Yémen': "yemen yemenite houthis houthi sanaa",
    'Émirats arabes unis': "emirats dubai dhabi",
    'Égypte': "egypte egyptien egyptienne egypt egyptian caire cairo",
    'Maroc': "maroc marocain marocaine morocco moroccan rabat casablanca",
    'Algérie': "algerie algerien algerienne algeria algerian alger",
    'Tunisie': "tunisie tunisien tunisienne tunisia tunisian tunis",
    'Sénégal': "senegal senegalais dakar",
    "Côte d'Ivoire": "ivoire ivoirien ivoirienne abidjan",
    'RD Congo': "rdc congo congolais kinshasa goma ituri tshisekedi m23",
    'Éthiopie': "ethiopie ethiopien ethiopia ethiopian addis tigre tigray",
    'Afrique du Sud': "sud-africain johannesburg pretoria",
    'Nigeria': "nigeria nigerian lagos abuja",
    'Chine': "chine chinois chinoise chinois china chinese pekin beijing shanghai",
    'Hong Kong': "hong",
    'Taïwan': "taiwan taiwanais taipei",
    'Japon': "japon japonais japonaise japan japanese tokyo osaka kyoto",
    'Corée du Sud': "coree-du-sud south-korea sud-coreen seoul",
    'Corée du Nord': "coree-du-nord north-korea nord-coreen pyongyang",
    'Inde': "inde indien indienne india indian delhi mumbai bombay modi",
    'Pakistan': "pakistan pakistanais islamabad karachi",
    'Afghanistan': "afghanistan afghan kaboul kabul taliban",
    'Thaïlande': "thailande thailandais thailand thai bangkok",
    'Australie': "australie australien australienne australia australian sydney melbourne canberra",
    'Nouvelle-Zélande': "nouvelle-zelande zealand auckland wellington",
    'Brésil': "bresil bresilien bresilienne brazil brazilian sao brasilia lula bolsonaro",
    'Argentine': "argentine argentin argentina argentinian buenos milei",
    'Mexique': "mexique mexicain mexicaine mexico mexican",
    'Colombie': "colombie colombien colombia colombian bogota",
    'Venezuela': "venezuela venezuelien caracas maduro",
    'Chili': "chili chilien chilienne chile chilean santiago",
    'Haïti': "haiti haitien port-au-prince",
    'Lettonie': "lettonie letton latvia latvian riga",
    'Malaisie': "malaisie malaysia lumpur",
    'Islande': "islande iceland reykjavik",
}
